version: "{branch}.{build}"
clone_folder: C:\Go-Work\src\github.com\dakraid\LooM
environment:
  GOPATH: C:\Go-Work
  CC: gcc.exe
  matrix:
    - GETH_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
install:
  - git submodule update --init
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://dl.google.com/go/go1.12.5.windows-%GETH_ARCH%.zip
  - 7z x go1.12.5.windows-%GETH_ARCH%.zip -y -oC:\ > NUL
  - go version
  - gcc --version
  - go get github.com/google/logger
  - go get github.com/andlabs/ui/...
  - go get github.com/go-sql-driver/mysql
  - go get golang.org/x/crypto/bcrypt
build_script:
  - cmd: go build -o LooM.exe github.com/dakraid/LooM